version: '3.8'
services:
  app:
    build: .
    ports:
      - "80:8080"
    env_file:
      - .env.prod
    restart: unless-stopped
    depends_on:
      - migrate

  migrate:
    build: .
    env_file:
      - .env.prod
    command: goose -dir ./migrations postgres "$DATABASE_URL" up
    restart: "no"
