name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to App Platform
      uses: digitalocean/app_action@v1.1.5
      with:
        app_name: moodle-api
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
